image: openjdk:17-jdk-alpine

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=true -Dorg.gradle.caching=true"

stages:
  - build
  - test
  - package
  - report
  - deploy

before_script:
  - export GRADLE_USER_HOME=cache/.gradle

cache:
  paths:
    - $GRADLE_USER_HOME/caches/
    - $GRADLE_USER_HOME/wrapper/
    - $GRADLE_USER_HOME/build-cache/

build:
  stage: build
  script:
    - ./gradlew --build-cache assemble --info
  artifacts:
    when: on_success
    paths:
      - build/classes

unit-test:
  stage: test
  script:
    - ./gradlew test --info
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml
    paths:
      - build/jacoco
      - build/reports/test

integration-test:
  stage: test
  script:
    - ./gradlew integrationTest --info
  artifacts:
    when: always
    reports:
      junit: build/test-results/integrationTest/**/TEST-*.xml
    paths:
      - build/jacoco
      - build/reports/integrationTest

ui-test:
  stage: test
  script:
    - export CHROME_OPTIONS=--headless
    - ./gradlew uiTest --info
  artifacts:
    when: always
    reports:
      junit: build/test-results/uiTest/**/TEST-*.xml
    paths:
      - build/jacoco
      - build/reports/uiTest

acceptance-test:
  stage: test
  script:
    - export CHROME_OPTIONS=--headless
    - ./gradlew acceptanceTest --info
  artifacts:
    when: always
    reports:
      junit: build/test-results/acceptanceTest/**/TEST-*.xml
    paths:
      - build/jacoco
      - build/reports/acceptanceTest

linting:
  stage: test
  script:
    - echo "Linting code... This will take about 10 seconds."

package:
  stage: package
  script:
    - echo "Packaging"

report-test-coverage:
  stage: report
  script:
    - ./gradlew jacocoTestReport --info
  artifacts:
    when: always
    paths:
      - build/reports/jacoco

deploy-dev:
  stage: deploy
  script:
    - echo "Deploying application to DEV..."
    - echo "Application successfully deployed."
